runtime: python312
env: standard
entrypoint: gunicorn -b :$PORT ftc.wsgi


handlers:
- url: /static              # new
  static_dir: staticfiles/  # new
- url: /media               # new
  static_dir: uploads/   # new
- url: /.*
  script: auto

runtime_config:
  python_version: 3