# Generated by Django 5.1.1 on 2024-09-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
