# Generated by Django 5.1.1 on 2024-09-27 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0002_update_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="update",
            name="summary",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.CreateModel(
            name="UpdateImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(null=True, upload_to="")),
                (
                    "update",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="update.update",
                    ),
                ),
            ],
        ),
    ]
