# Generated by Django 5.1.1 on 2024-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0004_rename_is_active_event_is_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
