# Generated by Django 5.1.1 on 2024-09-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0006_eventimage_alter_updateimages_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event",
                to="update.eventimage",
            ),
        ),
    ]
