# Generated by Django 5.1.1 on 2024-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0008_remove_event_image_eventimage_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="EventImage",
        ),
    ]
