# Generated by Django 5.1.1 on 2024-09-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0009_event_image_delete_eventimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("caption", models.CharField(max_length=200)),
                (
                    "event",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="update.event",
                    ),
                ),
            ],
        ),
    ]
