# Generated by Django 5.1.1 on 2024-09-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("update", "0010_remove_event_image_eventimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UpdateImages",
            new_name="UpdateImage",
        ),
    ]
