# Generated by Django 5.1.1 on 2024-10-03 08:33

import prose.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0013_alter_event_author_alter_eventimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=prose.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=prose.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=prose.fields.RichTextField(blank=True, default=''),
        ),
    ]
