name: Deploy to GAE

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      
      - name: Dotenv
        run: |
          echo ${{ secrets.DOT_ENV }} | base64 -d > .env
      
      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Connect to gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true
      
      - name: GCP Setup
        run: |
          echo ${{ secrets.GCP_CRED }} | base64 -d > gcpCredentials.json
      
      - name: Gather Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Run Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: dispatch.yaml app-prod.yaml
          version: v1
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
